### ISSUE TITLE
Working Example?

### ISSUE THREAD

**Issue by TronicLabs** [apoloval/flightvars#2]
If this is still in development, you might have a practical example of how to use it with P3D?

**Comment by apoloval** [comment]
Yes, it is still under development. I have no time enough to dedicate to it, but my plans are to work on FlightVars in the middle term. 

How to use it? Well, FlightVars would be a P3D plugin, very similar to FSUIPC. It is loaded when the sim boots and then it offers network connections to its clients to consume the data of the simulation.

I hope this helps.

(Since this is actually not an issue, I proceed to close it)
